name: Example
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matlab-actions/setup-matlab@v0
#      - uses: matlab-actions/run-tests@v0
#        with:
#          source-folder: source
#          code-coverage-cobertura: coverage.xml
      - uses: matlab-actions/run-command@v0
        with:
	  command: disp('hello world')
#	  source-folder: source
      - uses: codecov/codecov-action@v1
        with:
          file: coverage.xml